@Capitalead_HostAddress = http://localhost:5299

GET {{Capitalead_HostAddress}}/api/v1/run
Accept: application/json
###

GET {{Capitalead_HostAddress}}/api/v1/run-info
Accept: application/json
###

GET {{Capitalead_HostAddress}}/api/v1/find-duplicates
Accept: application/json
###

GET {{Capitalead_HostAddress}}/api/v1/migrate-sheets
Accept: application/json
###

GET {{Capitalead_HostAddress}}/api/v1/import-sheets
Accept: application/json
###

GET {{Capitalead_HostAddress}}/api/v1/calculate-kpi
Accept: application/json
###

GET {{Capitalead_HostAddress}}/api/v1/download-files
Accept: application/json
###

GET {{Capitalead_HostAddress}}/api/v1/export-file/leads telco fr 1.6M (1).xlsx
Accept: application/json
###

GET {{Capitalead_HostAddress}}/api/v1/create-db-files
Accept: application/json
###

GET {{Capitalead_HostAddress}}/api/v1/export-db-files
Accept: application/json
###
