@Capitalead_HostAddress = http://localhost:5298

GET {{Capitalead_HostAddress}}/api/v1/run
Accept: application/json
###

GET {{Capitalead_HostAddress}}/api/v1/find-duplicates
Accept: application/json
###
